# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow locates REST API file contracts
# (Swagger or OpenAPI format, v2 and v3, JSON and YAML)
# and runs 300+ security checks on them using 42Crunch Security Audit technology.
#
# Documentation is located here: https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a free 42Crunch account at https://platform.42crunch.com/register
#
# 2. Follow steps at https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#    to create an API Token on the 42Crunch platform
#
# 3. Add a secret in GitHub as explained in https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm,
#    store the 42Crunch API Token in that secret, and supply the secret's name as api-token parameter in this workflow
#
# If you have any questions or need help contact https://support.42crunch.com

name: "pr-workflow"

# follow standard Code Scanning triggers
on: 
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

env:
  PLATFORM_URL: https://demolabs.42crunch.cloud
  PLATFORM_SERVICE_ENDPOINT: services.demolabs.42crunch.cloud:8001
  TOKEN_ENV_VAR: ACCESS_TOKEN

permissions:
  contents: read

jobs:
  run_42c_audit:
    environment: 42Crunch
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for 42Crunch/api-security-audit-action to upload results to Github Code Scanning
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: get PR number
        id: getprnumber
        run: |
          pr_id=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR ID is:  $pr_id"
          echo "PR_ID=$pr_id" >> $GITHUB_OUTPUT
      - name: 42crunch-static-api-testing
        uses: 42crunch/api-security-audit-action@v3
        with:
          api-token: ${{ secrets.API_TOKEN }}
          platform-url: ${{ env.PLATFORM_URL}}
          default-collection-name: GitHubActions heshaam-42c/Pixi--${{ steps.getprnumber.outputs.PR_ID }}
          # Upload results to Github code scanning
          upload-to-code-scanning: true
          log-level: debug
          json-report: audit-action-report-${{ github.run_id }}
          sarif-report: audit-sarif-report-${{ github.run_id }}.sarif
          api-tags: Audit_Customizations:APIKeyHeaderAuth
      - name: save-audit-report
        if: always()   
        uses: actions/upload-artifact@v4
        with:
          name: auditaction-report-${{ github.run_id }}
          path: audit-action-report-${{ github.run_id }}.json
          if-no-files-found: error
      - name: save-sarif-report
        if: always()        
        uses: actions/upload-artifact@v4
        with:
          name: audit-sarif-report-${{ github.run_id }}
          path: audit-sarif-report-${{ github.run_id }}.sarif
          if-no-files-found: error    

  # We use the output of the previous step to scan the APIs       
  run_42c_scan:
    runs-on: ubuntu-latest
    needs: run_42c_audit
    environment: 42Crunch
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: download_audit_report    
        uses: actions/download-artifact@v4
        with:
          name: auditaction-report-${{ github.run_id }}
      # Get the API ID from the audit report
      - name: get pixi api id
        id: get_pixi_api_id
        run: |
          apiId=$(cat ./audit-action-report-${{ github.run_id }}.json | jq -r '.audit.report.${{ vars.PIXI_OAS_PATH }}.apiId')
          echo "PIXI_API_UUID=$apiId" >> $GITHUB_OUTPUT
          cat audit-action-report-${{ github.run_id }}.json
      # Scan V2
      - name: get_pixi_scan_conf_alias
        id: parse_alias
        run: |
          aliasId=$(cat ./.42c/conf.yaml | yq '.apis.${{ vars.PIXI_OAS_PATH }}.alias')
          echo "PIXI_SCAN_ALIAS=$aliasId" >> $GITHUB_OUTPUT
      - name: upload_v2_scan_config
        id: upload_v2_scan_config
        run: | 
            scanconfig_response=$(python .42c/scripts/scan_v2_config.py --quiet ${{ secrets.API_TOKEN }} ${{steps.get_pixi_api_id.outputs.PIXI_API_UUID}} -f .42c/scan/${{ steps.parse_alias.outputs.PIXI_SCAN_ALIAS }}/scanconf.json -n github-actions -p ${{env.PLATFORM_URL}})
            echo $scanconfig_response
            echo "SCANV2_TOKEN=$scanconfig_response" >> $GITHUB_OUTPUT
      - name: 42crunch-dynamic-api-testing
        run: |
            docker pull ${{vars.SCAN_AGENT_V2}}
            docker run -e SCAN_TOKEN=${{ steps.upload_v2_scan_config.outputs.SCANV2_TOKEN }} -e SCAN42C_HOST=${{ vars.PIXI_TARGET_URL }} -e PLATFORM_SERVICE=${{ env.PLATFORM_SERVICE_ENDPOINT }} ${{vars.SCAN_AGENT_V2}}
            
            echo "Retrieving Scan report URL"
            # List the scan reports for the target API and save the Task ID for github-actions
            taskId=$(python .42c/scripts/manage_scanv2_reports.py ${{ secrets.API_TOKEN }} ${{steps.get_pixi_api_id.outputs.PIXI_API_UUID}} -o list -p ${{ env.PLATFORM_URL}} -q | grep github-actions | cut -d',' -f1)
            configId=$(python .42c/scripts/manage_scanv2_reports.py ${{ secrets.API_TOKEN }} ${{steps.get_pixi_api_id.outputs.PIXI_API_UUID}} -o list -p ${{ env.PLATFORM_URL}} -q | grep github-actions | cut -d',' -f2)
            # Retrieve the scan report for the target API using Task ID
            python .42c/scripts/manage_scanv2_reports.py ${{ secrets.API_TOKEN }} ${{steps.get_pixi_api_id.outputs.PIXI_API_UUID}} -o retrieve -p ${{ env.PLATFORM_URL}} -t $taskId
            # Print the scan report URL using Scan Config ID
            echo "Scan report - ${{ env.PLATFORM_URL }}/apis/${{steps.get_pixi_api_id.outputs.PIXI_API_UUID}}/scan/report?configId=$configId"
      # - name: upload scan results
      #   uses: 42crunch/cicd-github-actions@v1.0.1
      #   with:
      #     api-token: ${{ secrets.API_TOKEN }}
      #     platform-url: ${{ env.PLATFORM_URL}}
      #     audit-report-path: audit-action-report-${{ github.run_id }}.json
      #     convert-to-sarif: scan-report-${{ github.run_id }}.sarif
      #     upload-sarif: true
      #     check-sqg: false
